### ISSUE TITLE
Could you assist with a question regarding the implementation of a GiOps bridge using Helm charts

### ISSUE THREAD

**Issue by akunduru9** [gitops-bridge-dev/gitops-bridge-helm-charts#4]
Can we use the Helm charts from this repository to implement a GitOps bridge? Additionally, do we need to have a separate namespace for GitOps, or should it be under any EKS-managed namespace?

**Comment by csantanapr** [comment]
Hi @akunduru9 
>Can we use the Helm charts from this repository to implement a GitOps bridge?

The gitops-bridge template already is updated to show an example on how to use these charts:
- https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/bootstrap/control-plane/addons/aws/addons-aws-csi-ebs-resources-appset.yaml#L17C1-L18C100
- https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/bootstrap/control-plane/addons/aws/addons-aws-fluentbit-fargate-appset.yaml#L17C1-L18C100
- https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/bootstrap/control-plane/addons/aws/addons-aws-oss-crossplane-upbound.yaml#L18C1-L19C100


>Additionally, do we need to have a separate namespace for GitOps, or should it be under any EKS-managed namespace?

You can specify any namespace to deploy helm charts using the Applications's `destination.namespace` like we do here https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/bootstrap/control-plane/addons/aws/addons-aws-oss-crossplane-upbound.yaml#L88

There are not EKS-managed namespaces, we create the `kube-system` namespace to store the aws-auth configmap, and recently is not required anymore. You can deploy you helm charts to `kube-system` or any other namespace you want, argocd can create the namespace when installing the helm chart

**Comment by csantanapr** [comment]
question addressed
